/* Oferta */
CREATE TABLE public.oferta
(
    id_oferta serial,
    id_webscraping integer,
    titulo character varying(200) COLLATE pg_catalog."default",
    empresa character varying(200) COLLATE pg_catalog."default",
    lugar character varying(100) COLLATE pg_catalog."default",
    tiempo_publicado character varying(100) COLLATE pg_catalog."default",
    salario character varying(100) COLLATE pg_catalog."default",
    modalidad_trabajo character varying(100) COLLATE pg_catalog."default",
    subarea character varying(100) COLLATE pg_catalog."default",
    url_oferta character varying(500) COLLATE pg_catalog."default",
    url_pagina character varying(500) COLLATE pg_catalog."default",
    area character varying(100) COLLATE pg_catalog."default",
    fecha_creacion date,
    fecha_modificacion date,
    oferta_detalle character varying(8000) COLLATE pg_catalog."default",
    fecha_publicacion date,
    time_publicacion character varying(60) COLLATE pg_catalog."default",
    id_anuncioempleo character varying(100) COLLATE pg_catalog."default",
    id_estado character(1) COLLATE pg_catalog."default",
    CONSTRAINT oferta_pkey PRIMARY KEY (id_oferta)
);


/* OfertaDetalle create */
CREATE TABLE public.oferta_detalle
(
    id_ofertadetalle serial,
    id_oferta integer NOT NULL,
    descripcion character varying(2000) COLLATE pg_catalog."default",
    descripcion_normalizada character varying(2000) COLLATE pg_catalog."default",
    ind_activo smallint,
    motivo_inactivo smallint,
    fecha_creacion date,
    fecha_modificacion date,
    ofertaperfil_id integer,
    CONSTRAINT oferta_detalle_pkey PRIMARY KEY (id_ofertadetalle)
);

/* Keywords */
CREATE TABLE public.keyword_search
(
    id_keyword serial,
    descripcion character varying(50) COLLATE pg_catalog."default",
    id_tipokeyword integer,
    CONSTRAINT keyword_search_pkey PRIMARY KEY (id_keyword)
);

/* insertamos */
-- INSERT INTO public.keyword_search( descripcion, id_tipokeyword)
-- VALUES 
--     ('ANALISTA PROGRAMADOR', 1),
--     ('ANALISTA DESARROLLO', 1),
--     ('ANALISTA DE SISTEMAS', 1),
--     ('ANALISTA FUNCIONAL', 1),
--     ('ANALISTA BPM', 1),
--     ('ANALISTA BI', 1),
--     ('ANALISTA CALIDAD TI', 1),
--     ('ANALISTA DE PROCESOS', 1),
--     ('ANALISTA TI', 1);

INSERT INTO public.keyword_search( descripcion, id_tipokeyword)
VALUES 
    	('ANALISTA PROGRAMADOR', 1),
    	('ANALISTA DESARROLLO', 1),
    	('ANALISTA DE SISTEMAS', 1),
  	 ('ANALISTA FUNCIONAL', 1),
    	('ANALISTA BPM', 1),
    	('ANALISTA BI', 1),
    	('ANALISTA CALIDAD TI', 1),
    	('ANALISTA DE PROCESOS', 1),
    	('ANALISTA TI', 1),
    	('DEVELOPER',1),
	('INGENIERO DE SISTEMAS'	,1),
	('INGENIERO DE SOFTWARE	',1),
	('INGENIERO INFORMATICO',1),
	('SOPORTE TECNICO',1),
	('FULLSTACK DEVELOPER',1),
	('ADMINISTRADOR DE REDES',1),
	('ADMINISTRADOR DE SERVIDORES',	1),
	('ADMINISTRADOR DE BASE DE DATOS',1),
	('COMPUTACION',1),
	('GERENTE DE SISTEMAS',1),
	('GERENTE DE INFORMATICA',1),
	('GERENTE DE TI',	1),
	('GESTOR DE PROYECTO TI',	1),
	('INGENIERO DE INFRAESTRUCTURA TI',1),
	('ARQUITECTO DE TI',1),
	('ARQUITECTO DE INTEGRACION',1),
	('ARQUITECTO DE SOLUCIONES',1),
	('ARQUITECTO DE SISTEMAS',1),
	('ARQUITECTO DE SOFTWARE',1),
	('ESPECIALISTA CLOUD',1),
	('ESPECIALISTA RED SOCIAL',1),
	('BUSINESS INTELIGENCE',	1),
	('CONSULTOR TI',	1),
	('TI CONSULTING',	1),
	('SUBGERENTE TI',	1),
	('SERVICIOS TI',1),
	('DATA MODELER',	1),
	('DATA ARCHITECT',1),
	('DATA ENGINEER',1),
	('DATA SCIENCE',2),
	('DATA ANALYTICS',2),
	('MACHINE LEARNING',2),
	('INTELIGENCIA ARTIFICIAL',2),
	('BIG DATA',2),
	('JAVA',2),
	('PYTHON',2),
	('ORACLE	',2),
	('POSTGRESQL',2),
	('MYSQL',2),
	('PHP',2),
	('POWER BUILDER',	2),
	('CYBERSEGURIDAD',2),
	('ITIL',2),
	('PMI',2),
	('SCRUM',2),
	('TRANSFORMACION DIGITAL',2),
	('SQL SERVER',2),
	('VUE',2),
	('JAVASCRIPT',2),
	('REACT',	2),
	('ANGULAR',2),
	('FRONT-END',2),
	('BACK-END',2),
	('ANDROID',2),
	('IOS',2),
	('KOTLIN',2),
	('.NET',2),
	('C#',2),
	('COBOL',	2),
	('FOX PRO',2),
	('RUBY',2),
	('REST',2),
	('SOAP',2),
	('APACHE',2),
	('MICROSERVICES',2),
	('DEVOPS',2),
	('SPRING',2),
	('HTML',	2),
	('WORDPRESS',2),
	('CLOUD',	2),
	('SAP',2),
	('GOOGLE	',2),
	('TWITTER',2),
	('BLOCKCHAIN',)	
	('COMPUTER SCIENCE',1),
	('COBIT',	2),
	('SEGURIDAD DE LA INFORMACION',	2),
	('GOBIERNO DE TI',2),
	('AUDITOR TI',1),
	('GOBERNANZA DE DATOS',	1),
	('TECNOLOGIA DE INFORMACION',2),
	('GESTION DEL CONOCIMIENTO',2),
	('GESTION DE LA INFORMACION',2),
	('GOBIERNO DIGITAL',2),
	('GOBERNANZA TI',2),
	('SOFTWARE',2),
	('SELENIUM',2),
	('QA AUTOMATION',1),
	('ANALISTA QA',1),
	('TEST DEVELOPER', 1),
	('ANALISTA DE PRUEBAS',1),
	('ANALISTA DE TESTING',1),
	('ANALISTA DE CALIDAD TI',1),
	('ANALISTA DE REDES',1),
	('ANALISTA DE SOPORTE',1),
	('WEB SERVICES',2),
	('MICROSERVICIOS',2),
	('REST FULL',2),
	('RIESGOS TI',1),
	('ARQUITECTO DE SEGURIDAD',1),
	('CONTINUIDAD DEL NEGOCIO',1),
	('ISO 27001',2),
	('ISO 27002',2),
	('CISA',2),
	('PMP',1),
	('ISO 22301',2),
	('CONTINUIDAD TI',1);

/* webscraping */
CREATE TABLE public.webscraping
(
    id_webscraping serial,
    busqueda character varying(100) COLLATE pg_catalog."default",
    busqueda_area character varying(100) COLLATE pg_catalog."default",
    pagina_web character varying(50) COLLATE pg_catalog."default",
    url_pagina character varying(500) COLLATE pg_catalog."default",
    url_busqueda character varying(500) COLLATE pg_catalog."default",
    fecha_creacion date,
    fecha_modificacion date,
    id_keyword integer NOT NULL,
    delati_team character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT webscraping_pkey PRIMARY KEY (id_webscraping)
);